version: '3'
services:
  redis:
    image: redis:6.0
    ports:
      - 16379:6379
  redis-cluster:
    image: grokzen/redis-cluster:latest
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
      - 7006:7006
    environment:
      - STANDALONE=1
  redis-sentinel:
    image: bitnami/redis-sentinel:6.0
    ports:
      - 26379:26379
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_SET=redis_sentinel
      - REDIS_SENTINEL_QUORUM=1
